### [作業目標]
1. 請接下列資料依照指定規則做合併：
- 依照 fruit 欄位做合併
- 依照 index 索引做合併
2. [簡答題] 承上題，請問為什麼依照 merge 合併後有些資料不見了？
3. [簡答題] 承上題，請問為什麼依照 index 合併會發生錯誤？請用程式解決。

### 1. 請接下列資料依照指定規則做合併：
- 依照 fruit 欄位做合併
- 依照 index 索引做合併

In [1]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'weight': ['high', 'medium', 'low'] * 3,
    'price': np.random.randint(0, 15, 9)
})

df2 = pd.DataFrame({
    'fruit': ['apple', 'orange', 'pine'] * 2,
    'weight': ['high', 'low'] * 3,
    'price': np.random.randint(0, 15, 6)
})
print(df1)
print(df2)

    fruit  weight  price
0   apple    high      9
1  banana  medium     10
2  orange     low     12
3   apple    high      9
4  banana  medium     12
5  orange     low      1
6   apple    high      9
7  banana  medium      0
8  orange     low      2
    fruit weight  price
0   apple   high     12
1  orange    low      2
2    pine   high      2
3   apple    low      6
4  orange   high      3
5    pine    low     10

In [2]:
# 依照 fruit 欄位做合併
pd.merge(df1, df2, on="fruit")

     fruit weight_x  price_x weight_y  price_y
0    apple     high        9     high       12
1    apple     high        9      low        6
2    apple     high        9     high       12
3    apple     high        9      low        6
4    apple     high        9     high       12
5    apple     high        9      low        6
6   orange      low       12      low        2
7   orange      low       12     high        3
8   orange      low        1      low        2
9   orange      low        1     high        3
10  orange      low        2      low        2
11  orange      low        2     high        3

In [3]:
# 依照 index 索引做合併
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['fruit', 'weight', 'price'], dtype='object')

### 2. [簡答題] 承上題，請問為什麼依照 merge 合併後有些資料不見了？

### <font color=#0000FF>Ans: pd.merge 預設為 inner join, 兩個 df 都有的資料才會合併</font>

### 3. [簡答題] 承上題，請問為什麼依照 index 合併會發生錯誤？請用程式解決。

### <font color=#0000FF>Ans: 因為原本的欄位重複，所以無法正確合併</font>

In [4]:
df1.join(df2, lsuffix="_df1", rsuffix="_df2")

  fruit_df1 weight_df1  price_df1 fruit_df2 weight_df2  price_df2
0     apple       high          9     apple       high       12.0
1    banana     medium         10    orange        low        2.0
2    orange        low         12      pine       high        2.0
3     apple       high          9     apple        low        6.0
4    banana     medium         12    orange       high        3.0
5    orange        low          1      pine        low       10.0
6     apple       high          9       NaN        NaN        NaN
7    banana     medium          0       NaN        NaN        NaN
8    orange        low          2       NaN        NaN        NaN